### PR TITLE
Fix diff display in case onEvents mutates the state object

### LINKED ISSUE #9: Both panes in the diff show the same (updated) state
Thanks again for sharing this, it's awesome <3. I may have found an issue, though.

When stepping through events, it seems to me that both panes in the diff view always show the same state.
At the very first event, the initial state is shown and diffed correctly. After that, no changes are displayed. 
Am I missing something?

timemachine

<details>
<summary>Twin definition</summary>

```ts
import { Fish, FishId, Pond, Tag } from '@actyx/pond'

type Robot = 'unknown' | 'robot A' | 'robot B' | 'robot C'
type State = {
  state: 'unknown' | 'open' | 'closed' | 'moving',
  requestedOpenDoor: Robot[],
}
type DoorOpenRequestedEvent = { eventType: 'doorOpenRequested', machineId: number, requestedBy: Robot }
type DoorMovementStartedEvent = { eventType: 'doorMovementStarted', machineId: number }
type DoorOpenedEvent = { eventType: 'doorOpened', machineId: number }
type DoorCloseRequestedEvent = { eventType: 'doorCloseRequested', machineId: number, requestedBy: Robot }
type DoorClosedEvent = { eventType: 'doorClosed', machineId: number }
type Event = DoorOpenRequestedEvent | DoorOpenedEvent | DoorCloseRequestedEvent | DoorClosedEvent | DoorMovementStartedEvent

const doorTag = Tag<Event>('machine')

const emitDoorOpenedEvent = (pond: Pond, doorId: string) => pond.emit(doorTag.withId(doorId), { eventType: 'doorOpened', machineId: 1 })
const emitDoorClosedEvent = (pond: Pond, doorId: string) => pond.emit(doorTag.withId(doorId), { eventType: 'doorClosed', machineId: 1 })
const emitDoorMovementStartedEvent = (pond: Pond, doorId: string) => pond.emit(doorTag.withId(doorId), { eventType: 'doorMovementStarted', machineId: 1 })

export const DoorFish = {
  tags: { doorTag },
  of: (name: string): Fish<State, Event> => ({
    fishId: FishId.of('example.doorFish', name, 0),
    initialState: { state: 'unknown', requestedOpenDoor: [] },
    where: doorTag.withId(name),
    onEvent: (state, event) => {
      switch (event.eventType) {
        case 'doorOpenRequested':
          state.requestedOpenDoor.push(event.requestedBy)
          break;
        case 'doorCloseRequested':
          state.requestedOpenDoor = state.requestedOpenDoor.filter(r => r !== event.requestedBy)
          break;
        case 'doorMovementStarted':
          state.state = 'moving'
          break;
        case 'doorOpened':
          state.state = 'open'
          break;
        case 'doorClosed':
          state.state = 'closed'
          break;
      }
      return state
    },
  }),
  emitDoorMovementStartedEvent,
  emitDoorOpenedEvent,
  emitDoorClosedEvent,
}
```
</details>

<details>
<summary>Twin Index</summary>

```ts
import { Fish } from '@actyx/pond'
import { DoorFish } from './test/time-machine/test-fish/door'

export default function (): Fish<any, any>[] {
  return [DoorFish.of('42')]
}
```
</details>

The actyx data folder containing the events from the gif above is attached.
[actyx-data.zip](https://github.com/actyx-contrib/time-machine/files/7060357/actyx-data.zip)

### PR DESCRIPTION
**Pull request by wwerner**
As written in #9, if a twin's `onEvent` mutates the state object (as opposed to returning a newly created state), the previous state gets overwritten (as it is a reference to the updated object).

To get around it, we can clone the state and put the clone into`previousState`.
This PR does that using `JSON.stringify/parse`, which might be considered hacky. Before dismissing it, note that both `Object.assign({},state)` and `{...state}` will lead to problems if `state` contains references, i.e. arrays or nested objects.
Another alternative would be using [lodash's `deepClone`](https://lodash.com/docs#cloneDeep), but that would introduce an additional dependency.

Closes #9

### CODE REVIEW

**Comment by wwerner** [comment]
timemachine-fixed

File: src/time-machine/actyx-functions.ts [hunk 1]
```diff
@@ -278,7 +278,7 @@ export function reduceTwinStateFromEvents(
   return events.reduce(
     (state, { payload, meta }) => {
       return {
-        previousState: state.currentState,
+        previousState: JSON.parse(JSON.stringify(state.currentState)), // clone previous state in case it gets mutated in onEvent
```
Comment (Alexander89) [inline src/time-machine/actyx-functions.ts]: this could have a surprising output. Without snapshots, the state doesn't need to be serializable.
I would suggest `lodash.clonedeep()` event if it adds one more dependency

Comment (wwerner) [reply src/time-machine/actyx-functions.ts]: Updated, although if its not serializable, it'll break the diff panel too, anyway.

Comment (wwerner) [reply src/time-machine/actyx-functions.ts]: I think that's a small edge case and would need some thinking about how to display such states or at least make sure that monaco doesn't choke on it, but using `lodash` does not hurt.

**Review by Alexander89 — APPROVED** [review]

**Review by sam-ln — APPROVED** [review]
